Repository SOPT-36-NINEDOT/NINEDOT-CLIENT, pull requests merged in 2025-09, with the labels that each got.

#180 Refactor: 전체 목표 뷰 리팩토링
  eslint.config.js
  src/api/axiosInstance.ts
  src/api/constant/queryKey.ts
  src/api/domain/edit/hook.ts
  src/api/domain/entireTodo/hook.ts
  src/api/domain/entireTodo/hook/useCreateMandalart.tsx
  src/api/domain/entireTodo/index.ts
  src/api/domain/entireTodo/type/entireTodo.ts
  src/api/domain/lowerTodo/hook/useOverallGoal.ts
  src/api/domain/myTodo/hook/useMyMandal.ts
  src/api/domain/upperTodo/hook.ts
  src/common/component/CycleDropDown/CycleDropDown.tsx
  src/common/component/GoButton/GoButton.tsx
  src/common/component/Loading/Loading.tsx
  src/common/component/UserModal/UserModal.tsx
  src/common/hook/useTypingEffect.ts
  src/page/home/hook/useFadeInOnView.ts
  src/page/intro/Intro.tsx
  src/page/signup/SignUp.tsx
  src/page/todo/entireTodo/Todo.css.ts
  src/page/todo/entireTodo/Todo.tsx
  src/page/todo/entireTodo/constant/typing.ts
  src/page/todo/lowerTodo/LowerTodo.tsx
  src/page/todo/upperTodo/UpperTodo.tsx
  src/page/todo/upperTodo/hook/useUpperTodoState.ts
  src/style/token/index.ts
  src/style/token/layout.css.ts
Labels: 🐵 지수, 🛠️ Refactor

#184 Refactor: AI 모달 리팩토링
  .nvmrc 2
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  pnpm-lock.yaml
  src/common/component/AiFailModal/AiFailModal.css.ts
  src/common/component/AiFailModal/AiFailModal.stories.tsx
  src/common/component/AiFailModal/AiFailModal.tsx
  src/common/component/AiModalBase/AiModalBase.css.ts
  src/common/component/AiModalBase/AiModalBase.tsx
  src/common/component/AiRecommendModal/AiRecommendModal.css.ts
  src/common/component/AiRecommendModal/AiRecommendModal.stories.tsx
  src/common/component/AiRecommendModal/AiRecommendModal.tsx
  src/common/component/Button/Button 2.tsx
  src/common/component/Modal/Modal.css.ts
  src/common/component/SelectableOption/SelectableOption.css.ts
  src/common/component/SelectableOption/SelectableOption.tsx
  src/common/hook/useModal.tsx
  src/common/hook/useOverlayModal.tsx
  src/main.tsx
  src/page/home/Home.tsx
  src/page/todo/lowerTodo/LowerTodo.tsx
  src/page/todo/upperTodo/UpperTodo.tsx
  src/shared/component/Layout/layoutHeader/Header.tsx
  src/style/token/layout.css.ts
Labels: 🐵 지수, 🛠️ Refactor

#196 [Refactor]: 나의 할 일 뷰 하단 리팩토링
  src/page/edit/component/Content/Content.tsx
  src/page/todo/myTodo/MyTodo.css.ts
  src/page/todo/myTodo/component/CycleChip/CycleChip.css.ts
  src/page/todo/myTodo/component/TodoBox/TodoBox.css.ts
  src/page/todo/myTodo/component/TodoCheckSection/TodoCheckSection.tsx
  src/page/todo/myTodo/hook/useMyTodo.ts
Labels: 🐵 지수, 🛠️ Refactor

#194 [Refactor] 나의 히스토리 뷰 리팩토링
  src/page/history/History.css.ts
  src/page/history/History.tsx
  src/page/history/StreakTrackerSection/StreakTrackerSection.css.ts
  src/page/history/StreakTrackerSection/StreakTrackerSection.tsx
  src/page/history/component/StreakDetail/StreakDetail.css.ts
  src/page/history/component/StreakDetail/StreakDetail.tsx
  src/page/history/component/index.ts
Labels: 🐰 새봄, 🛠️ Refactor

#199 [Refactor] 최초 진입 뷰 리팩토링
  src/App.tsx
  src/page/home/EndSection/EndSection.css.ts
  src/page/home/EndSection/EndSection.tsx
  src/page/home/Home.tsx
  src/page/home/ScrollSection/ScrollSection.css.ts
  src/page/home/ScrollSection/ScrollSection.tsx
  src/page/home/StartSection/StartSection.css.ts
  src/page/home/StartSection/StartSection.tsx
  src/page/home/constant/endSection.ts
  src/page/home/constant/messageConstants.ts
  src/page/home/constant/scrollSection.ts
  src/page/home/constant/startSection.ts
  src/page/home/index.ts
  src/page/home/type/lottieType.ts
  src/route/MainRoutes.tsx
Labels: 🐰 새봄, 🛠️ Refactor

#201 [Refactor] 나의 할 일 상단 리팩토링
  src/page/todo/myTodo/MyTodo.css.ts
  src/page/todo/myTodo/MyTodo.tsx
  src/page/todo/myTodo/component/RecommendSection/RecommendSection.tsx
  src/page/todo/myTodo/hook/useMyTodo.ts
Labels: 🐰 새봄, 🛠️ Refactor

#207 [Feat]: 404 페이지 구현
  src/page/index.ts
  src/page/notFound/NotFound.css.ts
  src/page/notFound/NotFound.tsx
  src/route/MainRoutes.tsx
  src/route/path.ts
Labels: ✨ Feature, 🐵 지수

#209 [Fix] 회원가입 에러 수정
  src/page/home/Home.tsx
  src/page/intro/Intro.tsx
  src/page/signup/SignUp.tsx
  src/shared/component/Layout/layoutHeader/Header.tsx
Labels: 🐞 Fix, 🐰 새봄

#219 [Fix]: QA 반영 - 푸터 외부 링크 연결
  src/route/path.ts
  src/shared/component/Layout/layoutFooter/Footer.tsx
Labels: 🐞 Fix, 🐵 지수

#221 [Fix]: QA 반영 - 만다라트 박스
  src/common/component/Mandalart/Square/Square.tsx
  src/common/component/TextField/modify/ModifyTextField.tsx
Labels: 🐞 Fix, 🐵 지수

#215 [Fix]: QA 반영 - 나의 할 일 뷰
  src/page/todo/myTodo/MyTodo.css.ts
  src/page/todo/myTodo/component/DatePicker/DatePicker.css.ts
  src/page/todo/myTodo/hook/useMyTodo.ts
  src/shared/component/Layout/Layout.css.ts
  src/style/global.css.ts
Labels: 🐞 Fix, 🌎 지수

#222 [Fix] QA 반영
  src/api/auth/googleLogin/authConstants.ts
  src/api/auth/googleLogin/util/generateGoogleLoginUrl.ts
  src/common/hook/useLoginModal.tsx
  src/page/home/Home.tsx
  src/route/LoginGuard.tsx
  src/route/MainRoutes.tsx
  src/shared/component/Layout/Layout.css.ts
  src/shared/component/Layout/layoutHeader/Header.css.ts
  src/shared/component/Layout/layoutHeader/Header.tsx
Labels: 🐞 Fix, 🐰 새봄, 🛠️ Refactor
