Repository SOPT-36-NINEDOT/NINEDOT-CLIENT, pull requests merged in 2025-07, with the labels that each got.

#22 [Init]: 디자인 토큰 설정
  index.html
  src/main.tsx
  src/style/.gitkeep
  src/style/global.css.ts
  src/style/reset.css.ts
  src/style/token/color.css.ts
  src/style/token/index.ts
  src/style/token/typography.css.ts
Labels: 🐰 새봄, ⚙️ Setting

#32 [Fix]: 키보드 이벤트 설정 해제
  eslint.config.js
Labels: 🐞 Fix, 🐰 새봄, ⚙️ Setting

#18 [Init]: Tanstack Query 기본 세팅
  package.json
  pnpm-lock.yaml
  src/common/util/.gitkeep
  src/common/util/queryClient.ts
  src/main.tsx
Labels: 🌎 지수, ⚙️ Setting

#38 [Feat]: 임시 헤더 및 rem 값 수정
  src/shared/component/Layout/Header/Header.css.ts
  src/shared/component/Layout/Header/Header.tsx
  src/shared/component/Layout/Layout.tsx
  src/style/global.css.ts
  src/style/token/typography.css.ts
Labels: ✨ Feature, 🐵 지수

#46 [Feat] 버튼 컴포넌트 제작
  package.json
  pnpm-lock.yaml
  public/svg/ic_big_next.svg
  src/assets/svg/IcBigNext.tsx
  src/assets/svg/index.ts
  src/common/component/GoButton/GoButton.css.ts
  src/common/component/GoButton/GoButton.tsx
  src/common/component/MandalButton/MandalButton.css.ts
  src/common/component/MandalButton/MandalButton.tsx
Labels: ✨ Feature, 🐰 새봄

#42 [Feat]: AI 추천 모달 컴포넌트 구현
  .storybook/main.ts
  public/svg/ic_checkbox_checked.svg
  public/svg/ic_checkbox_default.svg
  public/svg/ic_modal_delete.svg
  public/svg/vite.svg
  src/assets/svg/.gitkeep
  src/assets/svg/IcCheckboxChecked.tsx
  src/assets/svg/IcCheckboxDefault.tsx
  src/assets/svg/IcModalDelete.tsx
  src/assets/svg/Vite.tsx
  src/assets/svg/index.ts
  src/common/component/.gitkeep
  src/common/component/AiRecommendModal/AiRecommendModal.css.ts
  src/common/component/AiRecommendModal/AiRecommendModal.stories.ts
  src/common/component/AiRecommendModal/AiRecommendModal.tsx
  src/common/component/Modal/Modal.css.ts
  src/common/component/Modal/Modal.tsx
  src/common/hook/.gitkeep
  src/common/hook/useModal.tsx
  src/page/home/Home.tsx
  src/type/.gitkeep
  src/type/svg.d.ts
Labels: ✨ Feature, 🐵 지수

#50 [Feat]: 주기 드롭다운 컴포넌트 제작
  public/svg/ic_dropdown.svg
  src/assets/svg/IcDropdown.tsx
  src/assets/svg/index.ts
  src/common/component/CycleDropDown/CycleDropDown.css.ts
  src/common/component/CycleDropDown/CycleDropDown.tsx
  src/common/component/CycleDropDown/CycleList.css.ts
  src/common/component/CycleDropDown/CycleList.tsx
  src/common/component/GoButton/GoButton.css.ts
  src/common/component/MandalButton/MandalButton.css.ts
  src/style/reset.css.ts
  src/style/token/index.ts
  src/style/token/zIndex.css.ts
Labels: ✨ Feature, 🐰 새봄

#56 [Feat]: 만다라트 TextField 컴포넌트
  public/svg/ic_lock.svg
  public/svg/ic_textdelete.svg
  src/assets/svg/IcLock.tsx
  src/assets/svg/IcTextdelete.tsx
  src/assets/svg/index.ts
  src/common/component/MandalartTextField/MandalartTextField.css.ts
  src/common/component/MandalartTextField/MandalartTextField.stories.tsx
  src/common/component/MandalartTextField/MandalartTextField.tsx
  src/common/component/MandalartTextField/MandalartTextField.types.ts
  src/common/component/MandalartTextField/index.ts
  src/style/reset.css.ts
  src/style/token/color.css.ts
Labels: 🌎 지수, ✨ Feature

#62 [Feat]: Survey 컴포넌트 제작
  public/svg/ic_radio_checked.svg
  public/svg/ic_radio_default.svg
  src/assets/svg/IcRadioChecked.tsx
  src/assets/svg/IcRadioDefault.tsx
  src/assets/svg/index.ts
  src/page/signup/component/Survey/Survey.css.ts
  src/page/signup/component/Survey/Survey.tsx
  src/page/signup/component/Survey/data.ts
  src/page/signup/component/SurveyItem/SurveyItem.css.ts
  src/page/signup/component/SurveyItem/SurveyItem.tsx
  src/page/signup/component/type/optionType.ts
  src/page/signup/component/type/questionType.ts
Labels: ✨ Feature, 🐰 새봄

#71 [Fix]: prettier 설정 수정 및 전체 파일 포맷팅
  .github/ISSUE_TEMPLATE/✨-feature.md
  .github/ISSUE_TEMPLATE/🐞-fix.md
  .github/ISSUE_TEMPLATE/🛠️-refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/cd.yml
  README.md
  pnpm-lock.yaml
  tsconfig.json
Labels: 🐞 Fix, 🌎 지수

#65 [Feat]: 회원가입 TextField 컴포넌트
  public/svg/ic_small_textdelete.svg
  src/assets/svg/IcSmallTextdelete.tsx
  src/assets/svg/index.ts
  src/common/component/SignupTextField/RenderInputContent.tsx
  src/common/component/SignupTextField/SignupTextField.css.ts
  src/common/component/SignupTextField/SignupTextField.mock.ts
  src/common/component/SignupTextField/SignupTextField.tsx
  src/common/component/SignupTextField/SignupTextField.types.ts
  src/common/component/SignupTextField/constants.ts
  src/common/component/SignupTextField/index.ts
  src/common/component/SignupTextField/useSignupTextFieldState.ts
  src/common/component/SignupTextField/validation.ts
  src/common/util/format.ts
Labels: 🌎 지수, ✨ Feature

#84 [Feature]: 수정하기 TextField 컴포넌트
  public/svg/ic_medium_textdelete.svg
  src/assets/svg/IcMediumTextdelete.tsx
  src/assets/svg/index.ts
  src/common/component/ModifyTextField/ModifyTextField.css.ts
  src/common/component/ModifyTextField/ModifyTextField.tsx
  src/common/component/ModifyTextField/ModifyTextField.types.ts
  src/common/component/ModifyTextField/index.ts
  src/common/component/ModifyTextField/useModifyTextFieldState.ts
Labels: 🌎 지수, ✨ Feature

#96 [Feat]: Streack Tracker 섹션
  public/svg/ic_streaker_dot.svg
  public/svg/ic_streaker_dot_default.svg
  src/assets/svg/IcStreakerDot.tsx
  src/assets/svg/IcStreakerDotDefault.tsx
  src/assets/svg/index.ts
  src/page/history/History.css.ts
  src/page/history/History.tsx
  src/page/history/StreakTrackerSection/StreakTrackerSection.css.ts
  src/page/history/StreakTrackerSection/StreakTrackerSection.tsx
  src/page/history/component/StreakDetail/StreakDetail.css.ts
  src/page/history/component/StreakDetail/StreakDetail.tsx
  src/page/history/component/StreakGrid/StreakGrid.css.ts
  src/page/history/component/StreakGrid/StreakGrid.tsx
  src/page/history/sampleData/dayData.ts
  src/page/history/sampleData/todoData.ts
  src/page/history/type/StreakDataType.ts
Labels: ✨ Feature, 🐰 새봄

#106 [Feature]: cycleChip 컴포넌트 구현
  src/page/home/Home.tsx
  src/page/todo/myTodo/component/CycleChip/CycleChip.css.ts
  src/page/todo/myTodo/component/CycleChip/CycleChip.tsx
  src/page/todo/myTodo/component/CycleChip/index.ts
Labels: 🌎 지수, ✨ Feature

#102 [Feat]: Date Picker 컴포넌트 구현
  public/svg/ic_tomorrow.svg
  public/svg/ic_yesterday.svg
  src/assets/svg/IcTomorrow.tsx
  src/assets/svg/IcYesterday.tsx
  src/assets/svg/index.ts
  src/common/util/format.ts
  src/page/mandal/Mandal.tsx
  src/page/todo/myTodo/component/DatePicker/DatePicker.css.ts
  src/page/todo/myTodo/component/DatePicker/DatePicker.tsx
  src/page/todo/myTodo/component/DatePicker/index.ts
Labels: 🌎 지수, ✨ Feature

#94 [Feature]: TodoBox 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/page/home/Home.tsx
  src/page/todo/myTodo/component/TodoBox/TodoBox.css.ts
  src/page/todo/myTodo/component/TodoBox/TodoBox.tsx
  src/page/todo/myTodo/component/TodoBox/TodoBox.types.ts
  src/page/todo/myTodo/component/TodoBox/index.ts
  src/page/todo/myTodo/component/index.ts
Labels: 🌎 지수, ✨ Feature

#95 [Feat]: AI 추천 실패 모달 구현
  src/common/component/AiFailModal/AiFailModal.css.ts
  src/common/component/AiFailModal/AiFailModal.stories.ts
  src/common/component/AiFailModal/AiFailModal.tsx
  src/common/component/AiRecommendModal/AiRecommendModal.tsx
  src/common/component/Button/Button.css.ts
  src/common/component/Button/Button.tsx
  src/common/component/MandalButton/MandalButton.tsx
Labels: ✨ Feature, 🐵 지수

#131 [Feat] : 만다라트 전체 조회 API 연결
  src/api/constants/endPoint.ts
  src/api/domain/mandalAll/hook.ts
  src/api/domain/mandalAll/index.ts
  src/page/mandal/Mandal.tsx
  src/page/mandal/component/EntireMandal/EntireMandal.tsx
  src/page/mandal/mock/mandalartData.ts
  src/page/mandal/types/mandal.ts
Labels: 🕶️ 윤지, 📬 API

#125 [Feat]: 하위 목표 뷰 구현
  public/svg/ic_small_next.svg
  src/assets/svg/index.ts
  src/common/component/AiRecommendModal/AiRecommendModal.tsx
  src/common/component/CycleDropDown/CycleDropDown.css.ts
  src/common/component/CycleDropDown/CycleList.css.ts
  src/common/component/Mandalart/Mandalart.tsx
  src/common/component/Mandalart/Square/Square.css.ts
  src/common/component/MandalartTextField/MandalartTextField.tsx
  src/common/component/SignupTextField/validation.ts
  src/common/component/Tooltip/Tooltip.css.ts
  src/common/component/Tooltip/Tooltip.tsx
  src/page/todo/lowerTodo/LowerTodo.css.ts
  src/page/todo/lowerTodo/LowerTodo.tsx
  src/page/todo/lowerTodo/component/TodoFields.tsx
  src/page/todo/lowerTodo/mock.ts
  src/page/todo/lowerTodo/util.ts
  src/page/todo/upperTodo/UpperTodo.tsx
  src/route/MainRoutes.tsx
  src/style/token/zIndex.css.ts
Labels: 🌎 지수, ✨ Feature

#145 [Fix]: 버셀 로그인 문제 해결
  vercel.json
Labels: 🌐 Deploy, 🐰 새봄

#147 [Feat]: 라우터 수정
  src/page/home/EndSection/EndSection.tsx
  src/page/home/Home.tsx
  src/page/home/StartButton/StartButton.tsx
  src/page/home/StartSection/StartSection.tsx
  src/shared/component/Layout/layoutHeader/Header.css.ts
  src/shared/component/Layout/layoutHeader/Header.tsx
Labels: ✨ Feature, 🐰 새봄

#138 [Feat]: 나의 히스토리 API 연결
  src/api/auth/.gitkeep
  src/api/auth/googleLogin/Example.tsx
  src/api/constant/queryKey.ts
  src/api/domain/history/hook/useGetHistory.ts
  src/api/domain/history/hook/useGetStreak.ts
  src/api/domain/history/index.ts
  src/api/domain/history/type/historyResponse.ts
  src/api/domain/history/type/streakResponse.ts
  src/assets/image/history_background.svg
  src/assets/lottie/loading.json
  src/assets/lottie/mandalart.json
  src/common/component/Loading/Loading.css.ts
  src/common/component/Loading/Loading.tsx
  src/page/history/History.css.ts
  src/page/history/History.tsx
  src/page/history/StreakTrackerSection/StreakTrackerSection.css 2.ts
  src/page/history/StreakTrackerSection/StreakTrackerSection.tsx
  src/page/history/component/StreakGrid/StreakGrid.tsx
  src/page/history/sampleData/dayData 2.ts
  src/page/history/sampleData/dayData.ts
  src/page/history/sampleData/todoData.ts
  src/page/history/type/StreakDataType 2.ts
  src/page/history/type/StreakDataType.ts
  src/style/token/typography.css.ts
Labels: 🐰 새봄, 📬 API, 🛠️ Refactor

#154 [Feat]: 하위 목표 뷰 API 연동
  src/api/constant/queryKey.ts
  src/api/domain/edit/hook.ts
  src/api/domain/lowerTodo/hook/useAiRecommendSubGoal.ts
  src/api/domain/lowerTodo/hook/useCoreGoals.ts
  src/api/domain/lowerTodo/hook/useCreateSubGoal.ts
  src/api/domain/lowerTodo/hook/useSubGoalIds.ts
  src/api/domain/lowerTodo/hook/useSubGoals.ts
  src/api/domain/lowerTodo/index.ts
  src/api/domain/lowerTodo/type/aiRecommendSubGoal.ts
  src/api/domain/lowerTodo/type/coreGoals.ts
  src/api/domain/lowerTodo/type/createSubGoal.ts
  src/api/domain/lowerTodo/type/subGoalIds.ts
  src/api/domain/lowerTodo/type/subGoals.ts
  src/api/index.ts
  src/common/component/AiRecommendModal/AiRecommendModal.tsx
  src/common/component/CycleDropDown/CycleDropDown.tsx
  src/common/component/Mandalart/Mandalart.tsx
  src/common/component/Mandalart/Square/Square.css.ts
  src/common/component/MandalartTextField/MandalartTextField.tsx
  src/common/component/MandalartTextField/MandalartTextField.types.ts
  src/page/edit/hook/useMandalartHover.ts
  src/page/todo/lowerTodo/LowerTodo.tsx
  src/page/todo/lowerTodo/component/TodoFields.tsx
Labels: 🌎 지수, 📬 API

#159 [Feat]: 맞춤 할일 추천
  src/api/domain/myTodo/hook/useDeleteRecommendation.ts
  src/api/domain/myTodo/hook/usePostRecommendation.ts
  src/api/domain/myTodo/index.ts
  src/api/domain/myTodo/type/recommendation.ts
  src/page/todo/myTodo/hook/useMyTodo.ts
Labels: ✨ Feature, 🐰 새봄

#166 [Fix]: 요청 오류 해결
  src/page/todo/upperTodo/UpperTodo.tsx
Labels: 🐵 지수, 📬 API

#169 [Feat]: AI 추천 값 만다라트에 추가 연결
  src/api/domain/lowerTodo/index.ts
  src/common/component/AiFailModal/AiFailModal.tsx
  src/page/todo/lowerTodo/LowerTodo.tsx
Labels: 🌎 지수, 📬 API

#170 [Feat]: 페르소나 API 연결
  src/api/constant/endPoint.ts
  src/api/constant/queryKey.ts
  src/api/domain/signup/hook/useGetPersona.ts
  src/api/domain/signup/index.ts
  src/api/domain/signup/type/PersonaResponse.ts
  src/page/signup/SurveySection/SurveySection.tsx
Labels: ✨ Feature, 🐰 새봄

#171 [Feat]: favicon 적용
  index.html
  public/svg/favicon.svg
  public/svg/vite.svg
Labels: ✨ Feature, 🐵 지수

#165 [Feat]: 나의 할 일 하단 부분 API 연동
  src/api/constant/queryKey.ts
  src/api/domain/edit/index.ts
  src/api/domain/myTodo/hook/useMyMandal.ts
  src/api/domain/myTodo/index.ts
  src/api/domain/myTodo/type/myTodo.ts
  src/api/index.ts
  src/common/component/Mandalart/Mandalart.tsx
  src/page/todo/myTodo/MyTodo.tsx
  src/page/todo/myTodo/component/TodoBox/TodoBox.tsx
  src/page/todo/myTodo/component/TodoBox/TodoBox.types.ts
  src/page/todo/myTodo/component/TodoCheckSection/TodoCheckSection.tsx
  src/page/todo/myTodo/constant/mock.ts
  src/page/todo/myTodo/hook/useMyTodo.ts
Labels: 🐵 지수, 📬 API

#172 [Fix]: AI 추천 모달 스타일 수정
  src/common/component/AiRecommendModal/AiRecommendModal.css.ts
  src/common/component/AiRecommendModal/AiRecommendModal.tsx
Labels: 🎨 Design, 🐵 지수

#178 [Feat]: 하위 목표 뷰 남은 API 연결
  src/api/constant/queryKey.ts
  src/api/domain/lowerTodo/hook/useDeleteSubGoal.ts
  src/api/domain/lowerTodo/hook/useOverallGoal.ts
  src/api/domain/lowerTodo/hook/useUpdateSubGoal.ts
  src/api/domain/lowerTodo/index.ts
  src/api/domain/lowerTodo/type/updateSubGoal.request.ts
  src/common/component/MandalartTextField/MandalartTextField.css.ts
  src/common/component/MandalartTextField/MandalartTextField.tsx
  src/page/home/StartButton/StartButton.tsx
  src/page/todo/lowerTodo/LowerTodo.tsx
Labels: 🌎 지수, 📬 API
